/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jyyu' at '8/10/15 9:48 AM' with Gradle 2.5
 *
 * @author jyyu, @date 8/10/15 9:48 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
